project:
  type: website

website:
  title: "Ryan Romard"
  description: "Personal site of Ryan Romard, sociologist and research analyst"
  site-url: https://rromard.netlify.app
  image: main_preview.png
  twitter-card: true
  open-graph: true
  navbar:
    background: primary
    search: false
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about/index.qmd
      - text: Blog
        href: blog/index.qmd
      - text: Visuals
        href: visuals/index.qmd
      - text: Dashboards
        href: dashboards/index.qmd
      - text: Resources
        href: resources/index.qmd
  page-footer:
    background: primary
    left: © Ryan Romard 2024
    right: This website is built with [Bootswatch](https://bootswatch.com/) and [Quarto](https://quarto.org/)

format:
  html:
    theme: [lux, custom.scss]
    css: [styles.scss]
    toc: false
    page-layout: full

editor: visual

execute: 
  freeze: auto
